[mgr]
show_hidden = true
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
linemode = "none"

[[plugin.prepend_fetchers]]
url   = "*"
run   = "git"
group = "git"

[[plugin.prepend_fetchers]]
url   = "*/"
run   = "git"
group = "git"
