smart_borders on
smart_gaps on

# сделать рамки заметнее
default_border pixel 1
default_floating_border pixel 1

# цвета окна в фокусе / не в фокусе
client.focused           #7aa2f7 #7aa2f7 #ffffff #7aa2f7 #7aa2f7
client.unfocused         #333333 #222222 #888888 #292d2e #222222
client.focused_inactive  #444444 #333333 #cccccc #444444 #333333
client.urgent            #900000 #900000 #ffffff #900000 #900000
