# or input <identifier>
input "type:keyboard" {
    xkb_layout us,ru
    # xkb_variant ,nodeadkeys
    xkb_options grp:alt_shift_toggle,grp:win_space_toggle,caps:swapescape
}

input type:touchpad {
    dwt enabled
    tap enabled
    middle_emulation enabled
    natural_scroll enabled
}
