packages = [
  "zsh",
  "zsh_plugins",
  "zsh_agent",
  "fish",
  "yazi",
  "alacritty",
  "kitty",
  "vifm",
  "vlc",
  "tmux",
  "sway",
  "hypr",
  "waybar",
  "ashell",
  "mimeapps",
  "menus",
]
