packages = [
  "zsh",
  "zsh_plugins",
  "arc_autostart",
  "arc_autostart_macos",
  "arc_compdb",
  "zsh_agent",
  "fish",
  "yazi",
  "alacritty",
  "ssh_alacritty_url_handler",
  "kitty",
  "vifm",
  "vlc",
  "tmux",
  "karabiner",
]
